[package]
edition.workspace    = true
name                 = "chelix-providers"
repository.workspace = true
version.workspace    = true

[dependencies]
anyhow            = { workspace = true }
async-stream      = { workspace = true }
async-trait       = { workspace = true }
chelix-agents     = { path = "../agents" }
chelix-common     = { workspace = true }
chelix-config     = { workspace = true }
futures           = { workspace = true }
http              = { workspace = true }
jsonschema        = { workspace = true }
reqwest           = { workspace = true }
secrecy           = { workspace = true }
serde             = { workspace = true }
serde_json        = { workspace = true }
thiserror         = { workspace = true }
tokio             = { workspace = true }
tokio-stream      = { workspace = true }
tokio-tungstenite = { workspace = true }
tracing           = { workspace = true }

[dev-dependencies]
axum = { workspace = true }
http = { workspace = true }
toml = { workspace = true }

[lints]
workspace = true
