[package]
edition.workspace = true
name              = "chelix-auto-reply"
version.workspace = true

[dependencies]
chelix-common  = { workspace = true }
chelix-metrics = { optional = true, workspace = true }
tracing        = { workspace = true }

[features]
default = []
metrics = ["dep:chelix-metrics"]

[lints]
workspace = true
