[package]
edition.workspace = true
name              = "chelix-plugins"
version.workspace = true

[dependencies]
async-trait     = { workspace = true }
chelix-common   = { workspace = true }
chelix-config   = { workspace = true }
serde           = { workspace = true }
serde_json      = { workspace = true }
thiserror       = { workspace = true }
time            = { workspace = true }
tokio           = { workspace = true }
toml            = { workspace = true }
tracing         = { workspace = true }

[features]
default = []

[dev-dependencies]
tempfile = { workspace = true }
tokio    = { features = ["macros", "rt"], workspace = true }

[lints]
workspace = true
